### ISSUE TITLE
Fixed price for fuel (ex: $5/liter)

### ISSUE THREAD

**Issue by DreamManPT** [dev-callum/vrp-fuel#1]
Hi, first of all thank you very much for your effort and for sharing your work with others, secondly I would like to ask you for a little help regarding the script. I would like to set a fixed price for fuel (ex: $5/liter), how could I do this, I struggled a lot and I can't succeed, I'm not so good at programming ... I'm still learning. Thank you very much! <3

**Comment by regiments** [comment]
https://github.com/callum1337/vrp-fuel/blob/9f623079cf98b4a3352834aac72f6315a15ee2ae/config.lua#L8
